name: my_structure
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Default icons asset for Cupertino widgets based on Apple styled icons
  cupertino_icons: ^1.0.8
  # A powerful HTTP networking package, for API request
  dio: ^5.7.0
  # state management Bloc design pattern. Built to be used with the bloc state management package
  flutter_bloc: ^8.1.6
  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5
  # Easily create toast messages in single line of code
  fluttertoast: ^8.2.8
  # Flutter widgets for easily adding gaps inside Flex widgets such as Columns and Rows or scrolling views.
  gap: ^3.0.1
  # A Flutter package to check your internet connection with millisecond response times, even on mobile networks!
  internet_connection_checker_plus: ^2.5.2
  # for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^2.3.2
  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App
  get_it: ^8.0.2
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^2.4.0
  # A set of useful sliver tools that are missing from the flutter framework
  sliver_tools: ^0.2.12
  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing.
  intl: ^0.19.0
  # Easily add staggered animations to your ListView, GridView, Column and Row children as shown in Material Design guidelines
  flutter_staggered_animations: ^1.1.1
  # A collection of loading indicators animated with flutter. Heavily
  flutter_spinkit: ^5.2.1
  # A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^3.0.0
  # For App Localization
  easy_localization: ^3.0.7
  # For Responsive UI
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  flutter_lints: ^5.0.0
  # A command-line tool that simplifies the task of updating your Flutter app's launcher icon.
  icons_launcher: ^3.0.0
  # native splash screen with background color and splash image. Supports dark mode, full screen, and more.
  flutter_native_splash: ^2.4.2

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/fonts/
    - assets/images/

  fonts:

    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/roboto_condensed/RobotoCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto_condensed/RobotoCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/roboto_condensed/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto_condensed/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_condensed/RobotoCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_condensed/RobotoCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roboto_condensed/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_condensed/RobotoCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/roboto_condensed/RobotoCondensed-Black.ttf
          weight: 900

    - family: SairaSemiCondensed
      fonts:
        - asset: assets/fonts/saira_semi_condensed/SairaSemiCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/saira_semi_condensed/SairaSemiCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/saira_semi_condensed/SairaSemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/saira_semi_condensed/SairaSemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/saira_semi_condensed/SairaSemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/saira_semi_condensed/SairaSemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/saira_semi_condensed/SairaSemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/saira_semi_condensed/SairaSemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/saira_semi_condensed/SairaSemiCondensed-Black.ttf
          weight: 900

    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 900